---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# twitterbot
This package accesses documents from the [Open Archive HAL](https://hal.archives-ouvertes.fr/) and tweets the last scientific publications from the CRP2A laboratory ([\@CRP2Abib](https://twitter.com/crp2abib)).
    
## Installation

You you can install this R package from GitHub with:

```{r gh-installation, eval=FALSE}
# install.packages("devtools")
remotes::install_github("crp2a/twitterbot")
```

## Example

```{r bot, eval=FALSE}
library(twitterbot)

## Set the path of the log file
log_path <- file.path(Sys.getenv("HOME"), "bin", "twitter_hal.log")
## Read the log file
log_tweet <- twitterbot::readLog(file = log_path)

## Get documents from HAL
doc_hal <- twitterbot::getDocuments(id = "399901", limit = 100)
## Keep only the first ten new documents
doc_keep <- twitterbot::cleanDocuments(doc_hal, log = log_tweet, keep = 1:10)

## Compose and send
## Authenticate via access token
## See vignette("auth", package = "rtweet")
if (length(doc_keep) > 0) {
  ## Tweet 
  tweet <- vapply(
    X = doc_keep, 
    FUN = twitterbot::sendTweet,
    FUN.VALUE = logical(1),
    log = log_path,
    silent = TRUE
  )
}
```

Make a cron job to schedule tweets on a daily basis with [**cronR**](https://github.com/bnosac/cronR):

```{r cron, eval=FALSE}
library(cronR)

cmd <- cronR::cron_rscript(
  rscript = file.path(Sys.getenv("HOME"), "bin", "twitter.R"),
  rscript_log = file.path(Sys.getenv("HOME"), "bin", "twitter_cron.log"),
  cmd = file.path(Sys.getenv("R_HOME"), "bin", "Rscript"),
  log_append = TRUE
)

cronR::cron_add(
  command = cmd,
  frequency = "daily",
  at = "12:00",
  id = "CRP2Abib",
  tags = c("R", "HAL", "Twitter"),
  description = "CRP2A Twitter Bot",
  user = ""
)

# cronR::cron_njobs()
# cronR::cron_ls(id = "CRP2Abib")
# cronR::cron_clear(ask = FALSE)
```
